[package]

name = "ipc"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
libc = "0.1"

[dev-dependencies]
tempdir = "0.3"

[[test]]
name = "test"
path = "tests/test.rs"
harness = false
